version: '3'

services:
  moneytime.application.webapi.scheduling:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  moneytime.application.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  moneytime.application.webapi.mobile:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat


